### ISSUE TITLE
hello

### ISSUE THREAD

**Issue by Commandtechno** [tandpfun/DiscordTools#8]

**Comment by Commandtechno** [comment]
do you like my sussy boy
![amogus](https://user-images.githubusercontent.com/68407783/130042210-c3660801-a47a-4aee-86a8-cd66540a9dd2.png)

**Comment by Commandtechno** [comment]
i have another sussy boy do you like him
![image](https://user-images.githubusercontent.com/68407783/130042761-e77fbc2c-5d8b-463e-8abe-0bca9ee9c872.png)

**Comment by Commandtechno** [comment]
?

**Comment by tandpfun** [comment]
👍

**Comment by Commandtechno** [comment]
sorry
